#!/usr/bin/env python3
# Generated by Amazon Q, altered by Gary Denton

import boto3
import json
import os


def main():
    # Initialize AWS clients
    sts = boto3.client("sts")
    s3 = boto3.client("s3")

    # Get account ID
    account_id = sts.get_caller_identity()["Account"]

    # Create directory for account
    output_dir = f"{account_id}"
    os.makedirs(output_dir, exist_ok=True)

    # Get all S3 buckets
    buckets = s3.list_buckets()["Buckets"]

    print(f"Found {len(buckets)} S3 buckets in account {account_id}")

    for bucket in buckets:
        bucket_name = bucket["Name"]
        print(f"Processing bucket: {bucket_name}")

        try:
            # Get bucket region
            bucket_region = s3.get_bucket_location(Bucket=bucket_name)[
                "LocationConstraint"
            ]
            # Handle None (us-east-1) and eu-west-1 cases
            if bucket_region is None:
                bucket_region = "us-east-1"

            print(f"  Bucket region: {bucket_region}")

            # Create Config client for bucket's region
            config_regional = boto3.client("config", region_name=bucket_region)

            # Get configuration item for the bucket
            response = config_regional.get_resource_config_history(
                resourceType="AWS::S3::Bucket", resourceId=bucket_name, limit=1
            )

            if response["configurationItems"]:
                config_item = response["configurationItems"][0]

                # Convert datetime objects to strings for JSON serialization
                if "configurationItemCaptureTime" in config_item:
                    config_item["configurationItemCaptureTime"] = config_item[
                        "configurationItemCaptureTime"
                    ].isoformat()
                if "resourceCreationTime" in config_item:
                    config_item["resourceCreationTime"] = config_item[
                        "resourceCreationTime"
                    ].isoformat()

                # Write to JSON file
                output_file = os.path.join(output_dir, f"{bucket_name}.json")
                with open(output_file, "w") as f:
                    json.dump(config_item, f, indent=2, default=str)

                print(f"  ✓ Exported config for {bucket_name}")
            else:
                print(f"  ⚠ No config history found for {bucket_name}")

        except Exception as e:
            print(f"  ✗ Error processing {bucket_name}: {str(e)}")

    print(f"\nExport complete. Files saved in directory: {output_dir}/")


if __name__ == "__main__":
    main()
